# name: GitHub pages
# 
# on:
#   push:
#     branches:
#       - main
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       
#       - run: npm install
# 
#       - name: Build
#         uses: andstor/jsdoc-action@v1
#         with:
#           config_file: jsdoc.json
# 
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: github.ref == 'refs/heads/main'
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./docs